providers = ["python"]

[phases.setup]
nixPkgs = ['python310', 'gcc', 'postgresql']

[phases.install]
cmds = ['pip install --upgrade pip', 'ls -la', 'cd ./fruit_battlegrounds_wiki && pip install -r requirements.txt']

[start]
cmd = 'cd ./fruit_battlegrounds_wiki && gunicorn app:app' 