[phases.setup]
nixPkgs = ['python310', 'python310Packages.pip', 'gcc', 'postgresql']

[phases.install]
cmds = ['python -m pip install --upgrade pip', 'ls -la', 'cd ./fruit_battlegrounds_wiki && python -m pip install -r requirements.txt']

[start]
cmd = 'cd ./fruit_battlegrounds_wiki && python -m gunicorn app:app' 